version: "3.7"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        networks:
            - my-network
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        networks:
            - my-network
        ports:
            - '9092:9092'
        environment: 
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    sql:
        image: timbreidenstein/library-sql-oct2020:final
        networks:
            - my-network
        ports:
            - 1433:1433
    redis:
        image: redis:latest
        networks:
            - my-network
        ports:
            - 6379:6379
    reservationprocessor:
        image: timbreidenstein/reservationprocessor:latest
        networks:
            - my-network
        environment: 
            - kafka:bootstrapservers=kafka:9092
            - kafka:groupid=reservations-consumer
            - kafka:enableautocommit=true
            - kafka:securityprotocol=0
            - kafka:autooffsetreset=0
            - api=http://api:3000/
    api:
        image: timbreidenstein/libraryapi:latest
        ports:
            - 80:80
        networks:
            - my-network
        environment: 
            - ConnectionStrings__library=server=sql;database=books_prod;user=sa;password=TokyoJoe138!
            - ConnectionStrings__redis=redis
            - message=Hi
            - kafka:bootstrapservers=kafka:9092
networks:
    my-network:
        driver: bridge